In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train=pd.read_csv('C:\\Users\\Aayush Kandpal\\Downloads\\train.csv')
test=pd.read_csv('C:\\Users\\Aayush Kandpal\\Downloads\\test.csv')

In [3]:
train

,ID,Estimated_Insects_Count,Crop_Type,Soil_Type,Pesticide_Use_Category,Number_Doses_Week,Number_Weeks_Used,Number_Weeks_Quit,Season,Crop_Damage
0,F00000001,188,1,0,1,0,0.0,0,1,0
1,F00000003,209,1,0,1,0,0.0,0,2,1
2,F00000004,257,1,0,1,0,0.0,0,2,1
3,F00000005,257,1,1,1,0,0.0,0,2,1
4,F00000006,342,1,0,1,0,0.0,0,2,1
...,...,...,...,...,...,...,...,...,...,...
88853,F00155935,3337,1,0,2,10,12.0,44,3,0
88854,F00155938,3516,1,0,2,10,20.0,38,1,0
88855,F00155939,3516,1,0,2,15,40.0,8,2,0
88856,F00155942,3702,1,0,2,10,25.0,18,3,0
88857,F00155945,3895,1,0,2,20,37.0,7,3,0

In [3]:
train.Number_Weeks_Used.fillna(-99,inplace=True)
test.Number_Weeks_Used.fillna(-99,inplace=True)

In [4]:
train.isnull().sum()

ID                         0
Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
Crop_Damage                0
dtype: int64

In [5]:
test.isnull().sum()

ID                         0
Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [6]:
train['a1']=train[['Crop_Type','Soil_Type','Pesticide_Use_Category','Season']].mean(axis=1)
train['a2']=train[['Crop_Type','Soil_Type']].mean(axis=1)
train['a3']=train[['Pesticide_Use_Category','Season']].mean(axis=1)
train['a4']=train[['Estimated_Insects_Count', 'Crop_Type', 'Soil_Type',
       'Pesticide_Use_Category', 'Number_Doses_Week', 'Number_Weeks_Used',
       'Number_Weeks_Quit', 'Season']].mean(axis=1)
train['a5']=train[['Estimated_Insects_Count',
       'Pesticide_Use_Category', 'Number_Weeks_Used']].mean(axis=1)
train['a6']=train[[ 'Crop_Type', 'Soil_Type',
        'Number_Doses_Week',
       'Number_Weeks_Quit', 'Season']].mean(axis=1)
train['a7']=train[['Estimated_Insects_Count', 
        'Number_Weeks_Used','a4','a5','Pesticide_Use_Category','a1','a3'
       ]].mean(axis=1)



test['a1']=test[['Crop_Type','Soil_Type','Pesticide_Use_Category','Season']].mean(axis=1)
test['a2']=test[['Crop_Type','Soil_Type']].mean(axis=1)
test['a3']=test[['Pesticide_Use_Category','Season']].mean(axis=1)
test['a4']=test[['Estimated_Insects_Count', 'Crop_Type', 'Soil_Type',
       'Pesticide_Use_Category', 'Number_Doses_Week', 'Number_Weeks_Used',
       'Number_Weeks_Quit', 'Season']].mean(axis=1)
test['a5']=test[['Estimated_Insects_Count',
       'Pesticide_Use_Category', 'Number_Weeks_Used']].mean(axis=1)
test['a6']=test[[ 'Crop_Type', 'Soil_Type',
        'Number_Doses_Week',
       'Number_Weeks_Quit', 'Season']].mean(axis=1)
test['a7']=test[['Estimated_Insects_Count',
       'Number_Weeks_Used','a4','a5','Pesticide_Use_Category','a1','a3']].mean(axis=1)

In [7]:
train.columns

Index(['ID', 'Estimated_Insects_Count', 'Crop_Type', 'Soil_Type',
       'Pesticide_Use_Category', 'Number_Doses_Week', 'Number_Weeks_Used',
       'Number_Weeks_Quit', 'Season', 'Crop_Damage', 'a1', 'a2', 'a3', 'a4',
       'a5', 'a6', 'a7'],
      dtype='object')

In [8]:
cs=train.corr()
print(cs['Crop_Damage'])

Estimated_Insects_Count    0.202888
Crop_Type                 -0.016495
Soil_Type                 -0.021997
Pesticide_Use_Category     0.175002
Number_Doses_Week         -0.030874
Number_Weeks_Used          0.060401
Number_Weeks_Quit         -0.133117
Season                    -0.000184
Crop_Damage                1.000000
a1                         0.058184
a2                        -0.032399
a3                         0.095961
a4                         0.201940
a5                         0.204406
a6                        -0.100639
a7                         0.204250
Name: Crop_Damage, dtype: float64

In [56]:
train

,ID,Estimated_Insects_Count,Crop_Type,Soil_Type,Pesticide_Use_Category,Number_Doses_Week,Number_Weeks_Used,Number_Weeks_Quit,Season,Crop_Damage,a1,a2,a3,a4,a5,a6,a7
0,F00000001,188,1,0,1,0,0.0,0,1,0,0.75,0.5,1.0,23.875,63.000000,0.4,39.660714
1,F00000003,209,1,0,1,0,0.0,0,2,1,1.00,0.5,1.5,26.625,70.000000,0.6,44.160714
2,F00000004,257,1,0,1,0,0.0,0,2,1,1.00,0.5,1.5,32.625,86.000000,0.6,54.160714
3,F00000005,257,1,1,1,0,0.0,0,2,1,1.25,1.0,1.5,32.750,86.000000,0.8,54.214286
4,F00000006,342,1,0,1,0,0.0,0,2,1,1.00,0.5,1.5,43.250,114.333333,0.6,71.869048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88853,F00155935,3337,1,0,2,10,12.0,44,3,0,1.50,0.5,2.5,426.125,1117.000000,11.6,699.732143
88854,F00155938,3516,1,0,2,10,20.0,38,1,0,1.00,0.5,1.5,448.500,1179.333333,10.0,738.333333
88855,F00155939,3516,1,0,2,15,40.0,8,2,0,1.25,0.5,2.0,448.000,1186.000000,5.2,742.178571
88856,F00155942,3702,1,0,2,10,25.0,18,3,0,1.50,0.5,2.5,470.125,1243.000000,6.4,778.017857
88857,F00155945,3895,1,0,2,20,37.0,7,3,0,1.50,0.5,2.5,495.625,1311.333333,6.2,820.708333

In [90]:
test

,ID,Estimated_Insects_Count,Crop_Type,Soil_Type,Pesticide_Use_Category,Number_Doses_Week,Number_Weeks_Used,Number_Weeks_Quit,Season,a1,a2,a3,C
0,F00000002,188,1,1,1,0,28.705094,0,2,1.25,1.0,1.5,0
1,F00000007,410,1,1,1,0,0.000000,0,2,1.25,1.0,1.5,1
2,F00000011,626,1,0,1,0,0.000000,0,2,1.00,0.5,1.5,2
3,F00000013,731,1,0,1,0,0.000000,0,2,1.00,0.5,1.5,3
4,F00000014,789,0,0,1,0,0.000000,0,1,0.50,0.0,1.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59305,F00155937,3337,1,0,2,20,34.000000,12,1,1.00,0.5,1.5,59305
59306,F00155940,3516,1,0,2,20,32.000000,10,2,1.25,0.5,2.0,59306
59307,F00155941,3702,1,0,2,10,28.705094,48,1,1.00,0.5,1.5,59307
59308,F00155943,3702,1,0,2,10,28.000000,17,2,1.25,0.5,2.0,59308
59309,F00155944,3895,1,0,2,5,52.000000,7,1,1.00,0.5,1.5,59309

In [9]:
x=train.drop(['ID','Crop_Damage'],axis=1)
xt=test.drop(['ID'],axis=1)
y=train.Crop_Damage

In [9]:
train.shape,test.shape

((88858, 13), (59310, 12))

In [10]:
x.shape,xt.shape

((88858, 11), (59310, 11))

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val=train_test_split(x,y,random_state=0,test_size=0.2)

In [11]:
from lightgbm import LGBMClassifier
lgbm=LGBMClassifier(eval_metric='multi_error',objective='multiclass')

In [12]:
lgbm.fit(x_train,y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               eval_metric='multi_error', importance_type='split',
               learning_rate=0.1, max_depth=-1, min_child_samples=20,
               min_child_weight=0.001, min_split_gain=0.0, n_estimators=100,
               n_jobs=-1, num_leaves=31, objective='multiclass',
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [13]:
ypred=lgbm.predict(x_val)

In [14]:
ypred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
from sklearn.metrics import accuracy_score
print('Accuracy Score using LGBM:',accuracy_score(y_val,ypred))
from sklearn.metrics import classification_report
print(classification_report(y_val,ypred))

Accuracy Score using LGBM: 0.8483569660139545
              precision    recall  f1-score   support

           0       0.86      0.98      0.92     14848
           1       0.57      0.19      0.28      2473
           2       0.00      0.00      0.00       451

    accuracy                           0.85     17772
   macro avg       0.48      0.39      0.40     17772
weighted avg       0.80      0.85      0.81     17772